### ISSUE TITLE
could the project do sim2sim in mujoco or to real on h1 or go1 robot,

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#100]
@ZhengyiLuo ,Hello，could the project do sim2sim in mujoco or to real on h1 or go1 robo.If there are no privileged observations, can we train a policy for the student policy using only the robot's joint sensors, IMU sensors, and reference motion files as input? If so, could you provide a deployment example in MuJoCo? It would also be great if it could be transferred to a real GO1 or H1 robot.

**Comment by ZhengyiLuo** [comment]
In theory yes. We do our deployment in the [human2humanoid](https://github.com/LeCAR-Lab/human2humanoid) repo though.

**Comment by dbdxnuliba** [comment]
could you please provide an sim2sim example in mujoco  about h1 or go1  used trained result from phc or h2o
