### ISSUE TITLE
About Multi-Person Interaction

### ISSUE THREAD

**Issue by fengq1a0** [ZhengyiLuo/PHC#103]
Thank you for this excellent work! 
I'm interested in the "Real-time Physics-based Multi-Person Interaction from Video" demo on the PHC website.
Is the code for multi-person interaction included in this repo? Does the "HumanoidImMCPDemo" support it?
Currently, I'm trying to implement it myself.

**Comment by ZhengyiLuo** [comment]
It is largely included in this repo; just need a few tweaks. I implemented multi-person interactions by enabling the collision between two envs. Checkout the code [here](https://github.com/ZhengyiLuo/PHC/blob/a605cfd0772412fd2926f57a6dc3b467a845c4c7/phc/env/tasks/humanoid.py#L1050).
