### ISSUE TITLE
problems about writing the export_policy_as_jit() function.

### ISSUE THREAD

**Issue by smilefish110** [ZhengyiLuo/PHC#111]
Hello, sir!  Could you please show us how to export the model in jit format for deployment? I have problems while writing the export_policy_as_jit() function. Thank you very much! @ZhengyiLuo

**Comment by smilefish110** [comment]
I just found out that network input information cannot be obtained in real scenarios. So, is there any good way to solve the sim2real problem?
![2024-12-20 20-04-50屏幕截图](https://github.com/user-attachments/assets/3402db8d-f859-481f-b0d1-b73ebc81535b)

**Comment by ZhengyiLuo** [comment]
Hi! The policy trained in this repo is more suitable as a teacher policy for teacher-student distillation than direct deployment. For deployment on the real humanoid, please refer to the [H2O](https://github.com/LeCAR-Lab/human2humanoid) code base.

**Comment by smilefish110** [comment]
Thank you, sir!
