### ISSUE TITLE
Question on some parameters.

### ISSUE THREAD

**Issue by yunzeliu** [ZhengyiLuo/PHC#27]
Hi!

How is the `offset_height` parameter chosen in `language_to_pose_server.py`, and why is it necessary to perform a rotation operation on `gen_mdm_motions`?
And could you explain the processing flow for `gen_mdm_motions`? 

Thank you!

**Comment by yunzeliu** [comment]
And when I set `--num_envs 2`, how should I modify the code to pass in two identical `j3d` in `language_to_pose_server.py`? Are there any other revisions needed in `phc/run.py`?
Thanks a lot!

**Comment by ZhengyiLuo** [comment]
`offset_height` is to make sure that the reference motion is on the ground;

MDM generates the motion in a different coordinate system than isaac gym, so we need rotate it to make it the same coordinate system. The processing flow of `gen_mdm_motions` basically involves processing the output from MDM, convert them into the isaac coordinate system, handle the root position (make them continuous), and pass it to the simulator. 

For num_envs=2, basically you would need to generate two motions, and pass them to phc. Some modification would be needed in the `humanoid_im_mcp_demo.py` file.
