### ISSUE TITLE
how can i successfully install SMPL

### ISSUE THREAD

**Issue by Jayneh-yyds** [ZhengyiLuo/PHC#31]
I'm a newbie and I'm stuck here in the installation, can you tell me more about the installation content

**Comment by ZhengyiLuo** [comment]
Hi! 

The most basic inference code does not SMPL to run; you can move forward directly. 

If you want to install, create and account [here](https://smpl.is.tue.mpg.de/) and download the files according to the instructions in the README. 

Hope that helps!
