### ISSUE TITLE
Question about AMASS Dataset

### ISSUE THREAD

**Issue by Greatsjk** [ZhengyiLuo/PHC#35]
Thanks for your wonderful work. The mentioned steps for downloading the AMASS dataset. The AMASS has lots of options bodies to download(SMPL+H G SMPL-X G and so on). What should I download? Thanks for your patient.

**Comment by merc-s** [comment]
Hi @Greatsjk,

You may want to wait for confirmation by @ZhengyiLuo, but on my end downloading the SMPL-H models and slightly tweaking the loading scripts (one or two libraries from AMASS are missing) worked.

**Comment by ZhengyiLuo** [comment]
Hi! 

In PHC I used SMPL-H models.
