### ISSUE TITLE
Can't find amass_isaac_standing_upright_slim.pkl

### ISSUE THREAD

**Issue by WenjiaWang0312** [ZhengyiLuo/PHC#37]
Hi, author. Thanks for your contribution. But I cannot find `amass_isaac_standing_upright_slim.pkl` at all. Your download_data.sh also lacks this file I think. Please correct me if I am wrong.

**Comment by siyuzou** [comment]
check the line no.5 of[`download_data.sh`](https://github.com/ZhengyiLuo/PHC/blob/master/download_data.sh).

```bash
# gdown https://drive.google.com/uc?id=1fFauJE0W0nJfihUvjViq9OzmFfHo_rq0 -O  sample_data/ # sample standing neutral data.
```

somehow it is commented out.

**Comment by WenjiaWang0312** [comment]
Ok, Thank you!
