### ISSUE TITLE
How to get H36M-Motion

### ISSUE THREAD

**Issue by siyuzou** [ZhengyiLuo/PHC#41]
Hi ! @ZhengyiLuo 

I want to reproduce the results on H36M-Motion in your paper. Could you please share the pre-processing code of generating H36m-Motion dataset?

I tried to generate MotionLib pkl file on h36m motion provided by NeuralAnnot, but the results are awful :(

**Comment by ZhengyiLuo** [comment]
For h36m, I first run hyberik and metrabs on the raw videos, and then dump into pkl files [similar in this script](https://github.com/ZhengyiLuo/PHC/blob/master/scripts/data_process/convert_data_smpl.py). Some additional processing is done in a jupyter notebook (remove sequences; matching camera parameters).
