### ISSUE TITLE
ModuleNotFoundError: No module named 'smpl_sim.utils'

### ISSUE THREAD

**Issue by kunkun0w0** [ZhengyiLuo/PHC#44]
Thanks for releasing the PHC!!!!!

I met a problem when I tried to run `python scripts/vis/vis_motion_mj.py`
![image](https://github.com/ZhengyiLuo/PHC/assets/56219029/f973f220-972c-446a-81a3-b19546a738b2)

I also checked the `smpl_sim` and found no `utils` file or folder.
![image](https://github.com/ZhengyiLuo/PHC/assets/56219029/1661c467-8f0d-4fae-8da7-0fe3e6de8298)

I used the dockerfile in PHC.

**Comment by kunkun0w0** [comment]
I fixed it by manually copying the lost folder.

**Comment by xindonglin99** [comment]
Another thing that you can do is to install the smpl_sim with
```pip install -e git+https://github.com/ZhengyiLuo/SMPLSim.git@master#egg=smpl_sim```
See [this](https://stackoverflow.com/questions/10847764/after-installation-of-python-package-from-git-repository-some-folders-are-missin) for reference.
