### ISSUE TITLE
Use PHC+ for language-to-motion model

### ISSUE THREAD

**Issue by yw0208** [ZhengyiLuo/PHC#49]
Hi, great work.
I find you still use phc_kp_mcp_iccv in Language-to-motion Demo. 
I try to use PHC+ by the following command, but feel performance getting worse.
`python phc/run_hydra.py learning=im_mcp_big learning.params.network.ending_act=False exp_name=phc_comp_kp_2 env=env_im_getup_mcp env.task=HumanoidImMCPDemo robot=smpl_humanoid learning.params.network.ending_act=False robot.freeze_hand=True robot.box_body=False robot.real_weight_porpotion_boxes=False env.motion_file=sample_data/amass_isaac_standing_upright_slim.pkl env.models=['output/HumanoidIm/phc_kp_2/Humanoid.pth'] env.num_prim=3 env.num_envs=1 env.obs_v=7 headless=False epoch=-1 test=True no_virtual_display=True`
Is this command right? How should I fix it?
Thanks again.

**Comment by ZhengyiLuo** [comment]
Hi!

PHC+ is and PHC uses slightly different humanoid configuration, so the robot related commands should be 


```
robot=smpl_humanoid robot.real_weight_porpotion_boxes=False robot.freeze_hand=False robot.box_body=True
```

In them `robot.freeze_hand=False robot.box_body=True` is the default config in the yaml file so I didn't include them in the PHC+ commands now.
