### ISSUE TITLE
Linux version and vulkan DRI3 error

### ISSUE THREAD

**Issue by tomtang502** [ZhengyiLuo/PHC#51]
Hi, thank you for providing the code for your work.

Just want to make sure that which Linux os version did you use when running inference? It seem like ubuntu 22.04 kernel 28 is not working property by giving me vulkan no DRI3 error.

**Comment by ZhengyiLuo** [comment]
I used it on ubuntu 20.04 and Fedora 38. 

Maybe this thread could help? https://forums.developer.nvidia.com/t/can-isaac-gym-run-in-ubutu22-04/288777/2
