### ISSUE TITLE
Questions on training/testing with different SMPL shapes

### ISSUE THREAD

**Issue by zehongs** [ZhengyiLuo/PHC#52]
Hi Zhengyi, thank you for the excellent work!
I'm new to humanoid imitation learning and have a question. In the setting of obs_v=7 a uni-sized robot is used as the agent, are you using different betas in the training? I understand that different betas can result in varing keypoints sizes (e.g. very tall or very short reference targets). Is it better to keep the robot and target reference keypoints the same size?

**Comment by ZhengyiLuo** [comment]
Hi! depends on the robot config (flags like `has_shape_variation` will indicate whether to use different betas or not) I train models with or without body shape parameters. When training with different body shapes, I perform forward kinematics with the different body shapes to make sure that the keypoints are updated according to the new body shape. 

If no shape is involved, the neutral body shape is used.
