### ISSUE TITLE
Single Primitive Training (phc_prim) can't replicate result

### ISSUE THREAD

**Issue by Soumyabrata2003** [ZhengyiLuo/PHC#53]
Hi, I ran : 
python phc/run_hydra.py learning=im_big exp_name=phc_prim env=env_im robot=smpl_humanoid env.motion_file=sample_data/amass_isaac_standing_upright_slim.pkl
  
for single primitive training but the result is stagnating at 64% eval_success_rate (from 6k till >13k epochs). However, I had to change some configurations to accommodate for our single GPU setup's memory constraint. I had to reduce the batch size by decreasing the num_envs in env_im.yaml from 3072 to 512 and also had to reduce minibatch_size from 16384 to 2048 and amp_minibatch_size from 4096 to 512. Additionally, I reduced amp_obs_demo_buffer_size: 200000 & amp_replay_buffer_size: 200000 to 50000. Is this the reason the value is so less? How to mitigate this?

I even tried to keep the replay buffer sized at 200000 and only change the num_envs (=256) and mini_batch_sizes (1024 & 256 resp.) but the result is still the same.

Note: I had followed the preprocessing steps for AMASS and got a amass_isaac_im_train_take6_upright_slim.pkl file after finally running convert_amass_isaac.py which had 11.6k sequences, so I don't think there is any issue from the data's end.

**Comment by ZhengyiLuo** [comment]
Discussion moved to email.
