### ISSUE TITLE
No module named 'smpl_sim.khrylib'

### ISSUE THREAD

**Issue by ElviraLL** [ZhengyiLuo/PHC#54]
Thanks for this awesome work!

I was trying to process the SMPL data according to the provided document but met this error when importing `smpl_sim.khrylib`. I installed the environment using the requirement.txt file. Could you please take a look? Thanks!
```
  File "scripts/data_process/convert_amass_isaac.py", line 17, in <module>
    from smpl_sim.khrylib.utils import get_body_qposaddr
ModuleNotFoundError: No module named 'smpl_sim.khrylib'
```

**Comment by Soumyabrata2003** [comment]
Comment that line out. It isn't used in the code anyway. Worked for me.

**Comment by ElviraLL** [comment]
Thanks!

> Comment that line out. It isn't used in the code anyway. Worked for me.
