### ISSUE TITLE
Reduce Use of GPU Memory

### ISSUE THREAD

**Issue by yw0208** [ZhengyiLuo/PHC#58]
Hi, I added some complex scene meshes to the simulated environment. Then, the GPU memory is not enough.
Is there any way to reduce the memory PHC needs? For example, could I delete some unnecessary steps? All I need is to keep the function of motion imitation.
Looking forward to your reply. Thanks!

**Comment by yw0208** [comment]
Does PHC support to be run on multiple GPUs? If it does, how should I set it?

**Comment by ZhengyiLuo** [comment]
To reduce GPU memory, the easiest thing to do is to reduce the number of envs. Try `env.num_envs=1024`. 

I have never tried training PHC with multiple GPUs; it's certainly possible.
