### ISSUE TITLE
Managing deprecation of IsaccGym PSA

### ISSUE THREAD

**Issue by soulslicer** [ZhengyiLuo/PHC#61]
As you know, if you try to clone any repo that is using IsaccGym in the last N months, you will be faced with this page

![image](https://github.com/user-attachments/assets/d3de3625-c5a9-4938-9321-87aa37982813)

If you try to install and setup this repo anyway, you will be faced with a number of issues. Here is how to resolve them:

0. Setup your conda env and requirements.txt as suggested but use pytorch-gpu
1. First you will need to follow the seutp instructions for isacc gym as follows
```
# Installs IsaccGym
cd /home/{USER}/IsaacGym_Preview_4_Package/isaacgym/python; pip install .
# Sets the path needed to find `libpython3.8.so.1.0`
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/yaadhavraaj/miniconda3/envs/isaac/lib
# Sets up Vulkan needed by IsaccGym
sudo apt install vulkan-tools
export VK_ICD_FILENAMES=/home/{USER/IsaacGym_Preview_4_Package/isaacgym/docker/nvidia_icd.json
# Downgrades numpy since np.float was deprecated in 1.24
pip unstall numpy; pip install numpy==1.23.1
# Copies cpp bindings required to python site packages
cp -r /home/{USER}/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/   /home/{USER}/miniconda3/envs/isaac/lib/python3.8/site-packages/isaacgym/_bindings/
# Copies the pybind files (Make sure to download the pybind folder, you can get it from the pytorch repo)
cp -r pybind11 /home/{USER/miniconda3/envs/isaac/lib/python3.8/site-packages/torch/include/
```
2. Validate that you can run `python scripts/joint_monkey_smpl.py`

**Comment by ZhengyiLuo** [comment]
Excellent note! Could you create a pull request and add this to the readme as a note ([like this](https://github.com/ZhengyiLuo/PHC/blob/master/docs/smpl_robot_instruction.MD))? I will do a merge. 

Thanks!
