### ISSUE TITLE
Detailed explanation of parameters in 'amass_copycat_occlusion_v3.pkl'

### ISSUE THREAD

**Issue by Carmenw1203** [ZhengyiLuo/PHC#64]
Thank you for your great work! I notice that there are several types of 'issue' in 'amass_copycat_occlusion_v3.pkl'. But I'm confused about some of them. So may I ask for more detailed explanation of these 'issue'? For example, 'corruption' and 'airborne'.

**Comment by ZhengyiLuo** [comment]
`airborne` means that the human pose is floating; `corruption` means that the mocap data is corrupted (e.g. penetration or has discontinous frames).
