### ISSUE TITLE
Requiring for pretrained model weights.

### ISSUE THREAD

**Issue by zjuliangxun** [ZhengyiLuo/PHC#65]
Hi Luo, your interesting work inspired me a lot and I am planning to follow it. Specifically, I want to use the PHC to refine motions and finetune the control policy based on the PULSE. However, I find the model weights have not been released yet. Are you going to release them? It would be so time consuming if I train it from scratch.

**Comment by ZhengyiLuo** [comment]
Hi! Which model weights are you referring to? All of the models can be downloaded using bash download_data.sh.
