### ISSUE TITLE
isaacgym deprecated

### ISSUE THREAD

**Issue by robotNo201** [ZhengyiLuo/PHC#67]
I'm sorry, but isaac gym is deprecated, and no documentation can be searched.

**Comment by ZhengyiLuo** [comment]
I am in the process of adapting Isaac sim/lab. Documentation wise I think they release the docs together with the packages: 

https://forums.developer.nvidia.com/t/isaac-gym-documentation/202131

**Comment by PatP15** [comment]
Has there been any update on the release for Isaac lab?
