### ISSUE TITLE
Questions about Humanoid Robot Policy

### ISSUE THREAD

**Issue by zengweishuai** [ZhengyiLuo/PHC#74]
Hi Luo, thank you for releasing code for Unitree Robot!!!

For the Unitree policies, there are several questions expecting your reply:

1. Are those policies keypoint-based or rotation-based? Is there any guidance on how to change rotation-based policy into keypoint-based?
2. Is there any domain randomization applied during the training process?
3. Are these policies trained on the retargeted dataset which undergoes the same data cleaning process as you'd mentioned in H2O?

**Comment by ZhengyiLuo** [comment]
Hi, 

1. I did not release trained models with them but only the code support. You can change keypoint-based and rotation-based based on your need (obs_v=7 is keypoint based and obs_v=6 is rotation based). 
2. No domain randomization. I have started adding DR in the humanoid_teleop.py file but haven't tested in real-world yet. 
3. For deploying on the real-humanoid, please refer to policy released in [OmniH2O](https://github.com/LeCAR-Lab/human2humanoid).

**Comment by zengweishuai** [comment]
Thanks for your answer! This has helped a lot~
