### ISSUE TITLE
Hello, I would like to know what 'pose_aa' in the Omnih2o dataset is and why it is needed.

### ISSUE THREAD

**Issue by naivate** [ZhengyiLuo/PHC#78]
I'm sorry, I have one more question. If I already have dof_position, root_global_trans, and root_global_rot, how can I obtain the corresponding 'pose_aa'? Or rather, how can I integrate this with the Omnih2o code?

**Comment by ZhengyiLuo** [comment]
Pose_aa is the axis-angle representation. It's the 3D rotation corresponding to dof. It is needed for kinematic tree traversal.
