### ISSUE TITLE
Problems when using AMASS

### ISSUE THREAD

**Issue by Anonnyyy** [ZhengyiLuo/PHC#81]
您好！我希望测试单个动作的模仿效果。

1.我下载了几个（ACAAD和CMU的）数据集，转储到amass_db_smplh.pt文件后，在运行
python scripts/data_process/process_amass_db.py时，遇到以下问题：
python scripts/data_process/process_amass_db.py
  0%|                                                                              | 0/2331 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/data_process/process_amass_db.py", line 269, in <module>
    amass_seq_data = process_qpos_list(qpos_list)
  File "scripts/data_process/process_amass_db.py", line 169, in process_qpos_list
    amass_fr = v["mocap_framerate"]
KeyError: 'mocap_framerate'
请问如何解决？

2. 请问不同的动作pkl文件如何获得？是来自上述的步骤吗？（env.motion_file=sample_data/sample_dance_h1.pkl）
非常感谢！！！：）

**Comment by ZhengyiLuo** [comment]
1. Please try to use the `python scripts/data_process/convert_amass_data.py` script, which can directly process the AMASS dataset instead of the multi-step one I had before. 
2. For humanoid motion (like for H1), motion retargeting is needed.
