### ISSUE TITLE
AttributeError: module 'OpenGL.EGL' has no attribute 'EGLDeviceEXT'

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#85]
Hello ，when run the following command in the terminal ,and 
occurs Err:
(isaac) rob@rob:~/rl/PHC$ python scripts/vis/vis_motion_mj.py
Importing module 'gym_38' (/home/rob/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/rob/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
2024-11-06 13:09:43,061 - INFO - logger - logger initialized
MOVING MOTION DATA TO GPU, USING CACHE: False
MOVING MOTION DATA TO GPU, USING CACHE: False
!!!! Using modified SMPL starting pose !!!!
motion_file: sample_data/amass_isaac_standing_upright_slim.pkl
motion_data_list: []
Traceback (most recent call last):
  File "scripts/vis/vis_motion_mj.py", line 100, in <module>
    motion_lib = MotionLibSMPL(motion_lib_cfg)
  File "/home/rob/rl/PHC/phc/utils/motion_lib_smpl.py", line 49, in __init__
    super().__init__(motion_lib_cfg = motion_lib_cfg)
  File "/home/rob/rl/PHC/phc/utils/motion_lib_base.py", line 122, in __init__
    self.load_data(self.m_cfg.motion_file,  min_length = self.m_cfg.min_length, im_eval = self.m_cfg.im_eval)
  File "/home/rob/rl/PHC/phc/utils/motion_lib_base.py", line 158, in load_data
    self._motion_data_load = joblib.load(self._motion_data_load[0]) # set self._motion_data_load to a sample of the data 
IndexError: list index out of range

and here is the tree of the project
(isaac) rob@rob:~/rl/PHC$ tree -L 3
.
├── assets
│   ├── h1_phc.gif
│   ├── js
│   │   └── iframeResizer.contentWindow.min.js
│   ├── open3d.gif
│   ├── phc_teaser.gif
│   └── phc_x_teaser.gif
├── command.sh
├── data
│   └── smpl
│       ├── SMPL_FEMALE.pkl
│       ├── SMPL_MALE.pkl
│       ├── SMPL_NEUTRAL.pkl
│       ├── SMPLX_FEMALE.pkl
│       ├── SMPLX_MALE.pkl
│       └── SMPLX_NEUTRAL.pkl
├── docs
│   ├── Dockerfile
│   ├── docker_instruction.MD
│   ├── language_to_control_demo.md
│   ├── smpl_robot_instruction.MD
│   └── video_to_control_demo.md
├── download_data.sh
├── index.html
├── LICENSE
├── MUJOCO_LOG.TXT
├── phc
│   ├── data
│   │   ├── assets
│   │   ├── cfg
│   │   └── smpl
│   ├── env
│   │   ├── __init__.py
│   │   ├── tasks
│   │   └── util
│   ├── __init__.py
│   ├── learning
│   │   ├── amp_agent.py
│   │   ├── amp_datasets.py
│   │   ├── amp_models.py
│   │   ├── amp_network_builder.py
│   │   ├── amp_network_mcp_builder.py
│   │   ├── amp_network_pnn_builder.py
│   │   ├── amp_players.py
│   │   ├── ar_prior.py
│   │   ├── common_agent.py
│   │   ├── common_player.py
│   │   ├── im_amp_players.py
│   │   ├── im_amp.py
│   │   ├── __init__.py
│   │   ├── loss_functions.py
│   │   ├── masked_transformer_encoder.py
│   │   ├── mlp.py
│   │   ├── network_builder.py
│   │   ├── network_loader.py
│   │   ├── pnn.py
│   │   ├── replay_buffer.py
│   │   ├── running_norm.py
│   │   ├── transformer_layers.py
│   │   ├── transformer.py
│   │   ├── unrealego
│   │   └── vq_quantizer.py
│   ├── __pycache__
│   │   └── __init__.cpython-38.pyc
│   ├── run_hydra.py
│   ├── run.py
│   └── utils
│       ├── benchmarking.py
│       ├── config.py
│       ├── data_tree.py
│       ├── draw_utils.py
│       ├── flags.py
│       ├── __init__.py
│       ├── logger.py
│       ├── motion_lib_base.py
│       ├── motion_lib_real.py
│       ├── motion_lib_smpl.py
│       ├── o3d_utils.py
│       ├── parse_task.py
│       ├── plot_script.py
│       ├── __pycache__
│       ├── pytorch3d_transforms.py
│       ├── rotation_conversions.py
│       ├── running_mean_std.py
│       ├── torch_humanoid_batch.py
│       ├── torch_utils.py
│       └── traj_generator.py
├── poselib
│   ├── __init__.py
│   ├── poselib
│   │   ├── core
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   ├── skeleton
│   │   └── visualization
│   ├── __pycache__
│   │   └── __init__.cpython-38.pyc
│   ├── README.md
│   └── setup.py
├── README.MD
├── requirement.txt
├── runs
│   ├── Humanoid_14-16-31-42
│   │   └── summaries
│   ├── Humanoid_14-16-33-15
│   │   └── summaries
│   ├── Humanoid_17-22-41-51
│   │   └── summaries
│   └── Humanoid_17-22-50-15
│       └── summaries
├── scripts
│   ├── data_process
│   │   ├── convert_amass_data.py
│   │   ├── convert_amass_isaac.py
│   │   ├── convert_data_mdm.py
│   │   ├── convert_data_smpl.py
│   │   ├── fit_smpl_motion.py
│   │   ├── fit_smpl_shape.py
│   │   ├── process_amass_db.py
│   │   └── process_amass_raw.py
│   ├── demo
│   │   └── video_to_pose_server.py
│   ├── joint_monkey_smpl.py
│   ├── mdm_test.py
│   ├── mjcf_to_urdf.py
│   ├── phc_act
│   │   ├── create_phc_act_dataset.py
│   │   └── train_phc_actor.py
│   ├── pmcp
│   │   └── forward_pmcp.py
│   ├── quest_camera.py
│   ├── render_smpl_o3d.py
│   ├── vis
│   │   ├── vis_motion_mj.py
│   │   ├── vis_motion.py
│   │   ├── vis_q_mj.py
│   │   ├── vis_smpl_o3d_ego.py
│   │   ├── vis_smpl_o3d_multi.py
│   │   ├── vis_smpl_o3d.py
│   │   └── vis_smpl_o3d_single.py
│   └── ws_client.py
├── test_good.xml
└── test.xml

40 directories, 103 files

**Comment by XiaoWei-i** [comment]
Hi! I encounter the same problem. How did you solve it?
