### ISSUE TITLE
which one should we download in the amass

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#88]
which one should we download in the amass
![image](https://github.com/user-attachments/assets/d240e37a-10b2-46b2-bf9f-6997ef0b85de)

**Comment by IlanElfen** [comment]
all of them

**Comment by dbdxnuliba** [comment]
OK ,thanks, and which shoulder should I place them

**Comment by ZhengyiLuo** [comment]
All of them, and just decompress them each and put in one main folder. Would look something like this. 
<img width="516" alt="image" src="https://github.com/user-attachments/assets/e56cc9cc-276c-4e77-adc2-41f2f488139e">

**Comment by dbdxnuliba** [comment]
ok  many thanks!

**Comment by dbdxnuliba** [comment]
@IlanElfen @ZhengyiLuo sorry to trouble you , which one should we download SMPL+H G or SMPL-X G or SMPL-N

**Comment by dbdxnuliba** [comment]
ok , I see ,choose SMPL+H G
