### ISSUE TITLE
could you please give us a command to evluate g1 and h1 trained result

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#89]
could you please give us a command to evluate g1 and h1 trained result

the train command 
```
python phc/run_hydra.py project_name=Robot_IM robot=unitree_g1 env=env_im_g1_phc env.motion_file=sample_data/dance_sample_g1.pkl learning=im_pnn_big exp_name=unitree_g1_pnn sim=robot_sim control=robot_control learning.params.network.space.continuous.sigma_init.val=-1.7 
```
but what about the evalutation command about h1 or g1

**Comment by ZhengyiLuo** [comment]
Hi! H1 and G1 do not yet have a released model. Would that be of interest?

**Comment by dbdxnuliba** [comment]
> Hi! H1 and G1 do not yet have a released model. Would that be of interest?

Yes ,I'm very interested in indeed

**Comment by ghy0626-design** [comment]
Hi! I used the following command to train the G1 robot model:

python phc/run_hydra.py project_name=Robot_IM robot=unitree_g1 env=env_im_g1_phc env.motion_file=sample_data/dance_sample_g1.pkl learning=im_pnn_big exp_name=unitree_g1_pnn sim=robot_sim control=robot_control learning.params.network.space.continuous.sigma_init.val=-1.7

However, I’m not sure how to evaluate it. Could you provide me with a command or guidance on how to evaluate the trained model? Thanks!

**Comment by ghy0626-design** [comment]
> Hi! H1 and G1 do not yet have a released model. Would that be of interest?

Hi! I used the following command to train the G1 robot model:

python phc/run_hydra.py project_name=Robot_IM robot=unitree_g1 env=env_im_g1_phc env.motion_file=sample_data/dance_sample_g1.pkl learning=im_pnn_big exp_name=unitree_g1_pnn sim=robot_sim control=robot_control learning.params.network.space.continuous.sigma_init.val=-1.7

However, I’m not sure how to evaluate it. Could you provide me with a command or guidance on how to evaluate the trained model? Thanks!

**Comment by legnAray** [comment]
hi, do u know how to evaluate yet？
