### ISSUE TITLE
How can we use phc to produce the high dynamic motion file and polilcy and could you please give a correspding demo

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#90]
Thanks a lot for your nice work,

and the evalution comand you show is only stand still,
like amass_isaac_standing_upright_slim.pkl or stand_x_still  and coresponding command.

Question1：Could you please provide a demo of high dynamic motion and the correspding command the file
Question 2 ：How can we use phc to produce the high dynamic motion file and polilcy

like 
how can we get a  high dynamic motion  motion file  like your project  gif show
like that：
![1111](https://github.com/user-attachments/assets/70b9a979-26b6-4375-84c5-b3c4ce7e6d6f)

**Comment by ZhengyiLuo** [comment]
Hi! @dbdxnuliba 

So to do this, you will need to download the AMASS dataset, process it (and retarget if you want to use humanoids other than SMPL), and train imitators for them. For SMPL here I am using pretrained policy I released. For other humanoids, you can use the commands released to train them.

**Comment by dbdxnuliba** [comment]
thanks！
