### ISSUE TITLE
which one should we download SMPL+H G  or SMPL-X G  or SMPL-X N from amass dataset

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#93]
**which one should we download SMPL+H G  or SMPL-X G  or SMPL-X N from amass dataset**

> which one should we download in the amass ![image](https://private-user-images.githubusercontent.com/13350158/383578572-d240e37a-10b2-46b2-bf9f-6997ef0b85de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDM1NjEsIm5iZiI6MTczMTI0MzI2MSwicGF0aCI6Ii8xMzM1MDE1OC8zODM1Nzg1NzItZDI0MGUzN2EtMTBiMi00NmIyLWJmOWYtNjk5N2VmMGI4NWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEyNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMmY2ZDRjZGY4ZWQxMDk1YjdhYmM1MzI4ZmFiMWRiZjIwMzg1ZGNmN2ZkOGE1YjI1NzkzZWI5Y2ZlNWQwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pneJAyfjhs6vP8yn3KpY9Adl6kG7S2XnaeDvLBLBXpU)

**Comment by IlanElfen** [comment]
SMPL+H G

**Comment by dbdxnuliba** [comment]
ok,I see ,thanks


> SMPL+H G
