### ISSUE TITLE
I executed fit_smpl_motion on November 11, and by November 14, it still wasn't completed. I only put a small part of the dataset in. Why is this phenomenon occurring?

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#99]
@kexul @ZhengyiLuo Hello，sorry to trouble you
I executed the following on November 11, and by November 14, it still wasn't completed. I only put a small part of the dataset in. Why is this phenomenon occurring?

(isaac) rob@rob:~/rl/PHC$ python scripts/data_process/fit_smpl_motion.py robot=unitree_g1_fitting +fit_all=True
2024-11-11 23:06:33,853 - INFO - logger - logger initialized
2024-11-11 23:06:34,753 - DEBUG - Setting JobRuntime:name=UNKNOWN_NAME
2024-11-11 23:06:34,753 - DEBUG - Setting JobRuntime:name=fit_smpl_motion
key_names: ['0-ACCAD_Female1General_c3d_A2 - Sway_poses', '0-ACCAD_Female1General_c3d_A2 - Sway t2_poses', '0-ACCAD_Female1General_c3d_A1 - Stand_poses']
enter process_motion
enter process_motion
enter process_motion
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 137.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 112347.43it/s]
load forward kinematics model
load smpl model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 136.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 115628.99it/s]
load forward kinematics model
load smpl model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 114.48it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 117558.07it/s]
load forward kinematics model
load smpl model

From the added print information, it seems that it is known to be stuck at this statement
![NAME](https://github.com/user-attachments/assets/5a487571-a0a5-49bd-a92e-7749eb1f8977)

```
here is the dataset I put in only ACCAD folder， and only 3 npz files in it， 

rob@rob:~/rl/PHC/amass_data/Amass_part$ tree 
.
└── ACCAD
    └── Female1General_c3d
        ├── A1 - Stand_poses.npz
        ├── A2 - Sway_poses.npz
        └── A2 - Sway t2_poses.npz

2 directories, 3 files

here is the amas_root path
amass_root = "/home/rob/rl/PHC/amass_data/Amass_part"

**Comment by luoye2333** [comment]
3 motion clips should take less than 1 minute (several minutes at most). Do you remove the breakpoint in line 217?
```
import ipdb; ipdb.set_trace()
```

**Comment by IlanElfen** [comment]
I had the same issue. It works when you turn off multiprocessing (then it takes around a minute).
If you set num_jobs to 1, that should work, or process each file individually:
```
for pickle in all_pkls:
       all_pkls = [pickle]
       ...
       [the rest of the code in def main()]
```
But turning off multiprocessing increases the time if I want to retarget many files. The entire 16k AMASS motion files would take 7 days.
@luoye2333 Did you find a way to keep multiprocessing without it freezing?

**Comment by dbdxnuliba** [comment]
@luoye2333 @IlanElfen @ZhengyiLuo ，before run the command，if we run export OMP_NUM_THREADS=1
and then run the command ： python scripts/data_process/fit_smpl_motion.py robot=unitree_g1_fitting +fit_all=True，
3 motion clips should take less than 1 minute (several minutes at most).
